### ISSUE TITLE
Incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.

### ISSUE THREAD

**Issue by connected-whunt** [hannesa2/paho.mqtt.android#128]
Hey not sure if this is a real bug here, but i can't solve it. I think it may have something to do with the expected android studio Kotlin plugin. Current plugin here : 202-1.5.10-release-894-AS81294.7

Kotlin version in gradle, 1.3.70 , 1.3.72 both do not work.

Otherwise 2.1 of this lib works, thanks for keeping it up to date!

**Comment by hannesa2** [comment]
Can you share more info ? To be honest, I've no clue what you are writing about. Best would be a repository (with error prone branch)

**Comment by connected-whunt** [comment]
Hey, I solved the problem with a bit of experimentation. I can give a fairly empty demo project here https://github.com/connected-whunt/testingPahoBug
But the issue seems to resolve by setting the kotlin_version to "1.4.0" or greater for the project using this.
Within the project level gradle
buildscript {
    ext.kotlin_version = "1.4.0"
    ....
        dependencies {
        classpath "com.android.tools.build:gradle:4.2.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        ...
        
Relevant part from the app gradle
dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    ...

**Comment by hannesa2** [comment]
Glad you solved it !

Indeed checking out our repo runs automatic into
<img width="825" alt="image" src="https://user-images.githubusercontent.com/3314607/122607392-c420bf00-d07a-11eb-8bdb-330ccd54e5b6.png">

But this solves it `ext.kotlin_version = "1.4.32"`
