### ISSUE TITLE
about qos level question

### ISSUE THREAD

**Issue by protectedMan** [hannesa2/paho.mqtt.android#192]
What I understand is that when QoS = 2, the data pushed by the Android client will timeout when the network is disconnected and will be pushed again after the network is restored.
However, in actual use, I found that some mobile phones will not push again after the network is restored.
Why does this happen?

**Comment by hannesa2** [comment]
> ... the data pushed by the Android client will timeout when the network is disconnected and will be pushed again after the network is restored.

It's my understanding too.

And sorry, you did more investigation on different devices. An Espresso test for this would be cool
