### ISSUE TITLE
MqttAndroidClient override wrong disconnect function

### ISSUE THREAD

**Issue by vuptt** [hannesa2/paho.mqtt.android#209]
In disconnect functions interface they specfify userContext object is nullable, but it become non null in MqttAndroidClient implementation class

userContext – optional object used to pass context to the callback. Use null if not required.
callback – optional listener that will be notified when the disconnect completes. Use null if not required.

`IMqttToken disconnect(long quiesceTimeout, Object userContext, IMqttActionListener callback) throws MqttException;`

MqttAndroidClient class code:

`override fun disconnect(quiesceTimeout: Long, userContext: Any, callback: IMqttActionListener): IMqttToken `

**Comment by hannesa2** [comment]
Sorry, I can't follow you. 
Please can you make a pull request to solve this. Then I exactly see what you mean and merge it

**Comment by vuptt** [comment]
Sure

**Comment by vuptt** [comment]
@hannesa2 can you check #210
