### ISSUE TITLE
Auto reconnect doesn't work after losing internet connection

### ISSUE THREAD

**Issue by rushsports** [hannesa2/paho.mqtt.android#231]
My MqttClient implementation based on your basicSample: https://pastebin.com/KzQEAsXj
connectionLost callback work correctly, but after the internet connection is restored is not called connectComplete callback or some other

**Comment by hannesa2** [comment]
The basicSample is somehow broken anyways

**Comment by hoangchungk53qx1** [comment]
the same issues

**Comment by hannesa2** [comment]
Please follow https://github.com/hannesa2/paho.mqtt.android/tree/master/extendedSample
