### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter exception

### ISSUE THREAD

**Issue by chihung93** [hannesa2/paho.mqtt.android#233]
Version :   "com.github.hannesa2:paho.mqtt.android:3.1.1"

Firebase reported this issue

<img width="1321" alt="Screen Shot 2021-10-16 at 15 03 05" src="https://user-images.githubusercontent.com/5199109/137579743-2be4eee9-aaab-47d2-a74f-ab06e57232bd.png">

Do you have any solution for this?

**Comment by hannesa2** [comment]
The main question is why is there no `throwable` ? 
I would love, when you could explain it to me.
