### ISSUE TITLE
ReadMe's instruction does not work with the latest Android Studio.

### ISSUE THREAD

**Issue by HubKing** [hannesa2/paho.mqtt.android#245]
All the instruction available is the thing at the bottom. However it does not seem to work with default project template created by the latest Android Studio. After struggling with errors, I have found [a solution](https://stackoverflow.com/questions/66475730/in-android-studio-arctic-fox-canary-8-the-app-level-build-gradle-does-not-gener). It was adding the following to settings.gradle file

    maven { url 'https://jitpack.io' }

below other repositories. Please add that to the instruction so that people would not waste time as I did.

----

```
  allprojects {
    repositories {
      ...
      maven { url 'https://jitpack.io' }
    }
  }
```
```
dependencies {
  implementation 'androidx.legacy:legacy-support-v4:1.0.0'
  implementation 'com.github.hannesa2:paho.mqtt.android:$latestVersion'
}
```

**Comment by hannesa2** [comment]
On my side `settings.gradle` file definitely needs no

`maven { url 'https://jitpack.io' }`
