### ISSUE TITLE
room database error

### ISSUE THREAD

**Issue by 4563599** [hannesa2/paho.mqtt.android#269]
hello,hannesa2:
 I use your fork.
  2022-01-15 10:31:35.879 10342-10831/com.philips.easykey.lock E/SQLiteLog: (1) no such table: room_table_modification_log in "SELECT * FROM room_table_modification_log WHERE invalidated = 1;"
2022-01-15 10:31:35.881 10342-10831/com.philips.easykey.lock E/ROOM: Cannot run invalidation tracker. Is the db closed?
    android.database.sqlite.SQLiteException: no such table: room_table_modification_log (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM room_table_modification_log WHERE invalidated = 1;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1047)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:654)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1546)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1521)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:183)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:530)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:513)
        at androidx.room.InvalidationTracker$1.checkUpdatedTable(InvalidationTracker.java:458)
        at androidx.room.InvalidationTracker$1.run(InvalidationTracker.java:431)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

please help me

**Comment by hannesa2** [comment]
it looks like the database is broken. It tries to read table modification, but there are no specified `const val MQ_DB_VERSION = 1`
Th most interested questions is why does it happen, here you can provide more information. 
What do you do with `MqttAndroidClient` or with `MqttService` ? Is it closed and restored,.... ?

As a workaround you have to remove database anyhow, by reinstall or similar steps

**Comment by hannesa2** [comment]
Do you use version `3.3.4` ?

**Comment by 4563599** [comment]
yes, i am using 3.3.4.



发自我的iPhone


------------------ Original ------------------
From: Hannes Achleitner ***@***.***&gt;
Date: Mon,Jan 17,2022 1:50 PM
To: hannesa2/paho.mqtt.android ***@***.***&gt;
Cc: 4563599 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [hannesa2/paho.mqtt.android] room database error (Issue #269)





 
Do you use version 3.3.4 ?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 4563599** [comment]
I search this problem on google.  this https://stackoverflow.com/questions/50370683/room-migration-no-such-table-room-table-modification-log  seems the same program.
I found a rule, when I log out of the account and use the MQTT function again, this problem will occur。

**Comment by hannesa2** [comment]
But there is no migration at all. It looks like db is broken anyhow. You see it, when db tries to read migration log

**Comment by hannesa2** [comment]
> I found a rule, when I log out of the account and use the MQTT function again, this problem will occur。

The sample MQ-server `mqtt.eclipseprojects.io` looks like having [issues](https://github.com/hannesa2/paho.mqtt.android/pull/270), that's why I've no test server anymore.
That means, only you can test currently. Please have a look on `MqttAndroidClient` and `MqttService` during logout and relogin

**Comment by 4563599** [comment]
how can I have a look on MqttAndroidClient and MqttService during logout and relogin?
please tell me how can I do for you,ths!

**Comment by hannesa2** [comment]
Here https://github.com/hannesa2/paho.mqtt.android/blob/master/serviceLibrary/src/main/java/info/mqtt/android/service/MqttService.kt#L201 the database is opened.

And here https://github.com/hannesa2/paho.mqtt.android/blob/master/serviceLibrary/src/main/java/info/mqtt/android/service/MqttService.kt#L215 it's closed. 

In the `.close()` there is from Room some lock mechanism. 
<img width="543" alt="image" src="https://user-images.githubusercontent.com/3314607/149723207-77711c17-18e8-4bb6-8ea5-b12ccf20bdff.png">

Maybe it's the root cause ?

I would look into close, if it's called, when it's called. And what happens in close(). And how does the new open() impact this all

**Comment by 4563599** [comment]
you can drop the  //messageStore.close()  in  fun onDestroy and then can you publish a new version 3.3.5 on github?  I can help you have a test for this issues. Thanks!

**Comment by hannesa2** [comment]
Did you tested it without it. Is there an improvement, or is this just a slow test try ?

**Comment by 4563599** [comment]
My company project used to use the paho.mqtt.android which is https://github.com/eclipse/paho.mqtt.android.But it doesn't work on android 12, so I used your branch, but it works on both android 9 and android 12 this problem occurs,I want to solve this problem as soon as possible for your help.Thanks you !

**Comment by hannesa2** [comment]
Please try `implementation 'com.github.hannesa2:paho.mqtt.android:3.3.4.1'`

**Comment by 4563599** [comment]
I seems work when i use the 3.3.4.1 version. No SQLITE_ERROR occur。
Thanks very much and I will do more test for this problem!
you can get more info the ROOM fun close() when to use.
Thank you!

**Comment by hannesa2** [comment]
Cool, when you test more ! 
Please use `com.github.hannesa2:paho.mqtt.android:3.3.4.2` It comes with an update of Room.

Please ping me, when your tests are done and I'll merge #271 and I'll create `3.3.5` and drop `3.3.4.1` and `3.3.4.2`. (These are tags based on a branch and I want to avoid this)

**Comment by hannesa2** [comment]
Sorry for the confusion but I changes version number immediate. I deleted `3.3.4.1` and `3.3.4.2`
Please use `3.3.5-beta2` for your tests now.

**Comment by 4563599** [comment]
> Sorry for the confusion but I changes version number immediate. I deleted `3.3.4.1` and `3.3.4.2` Please use `3.3.5-beta2` for your tests now.

OK ths,

**Comment by hannesa2** [comment]
@sisier https://github.com/hannesa2/paho.mqtt.android/issues/272 is the same error with `3.3.5-beta2`

> Thanks very much and I will do more test for this problem!

@4563599 What's your observation ?

**Comment by 4563599** [comment]
> @sisier #272 is the same error with `3.3.5-beta2`
> 
> > Thanks very much and I will do more test for this problem!
> 
> @4563599 What's your observation ?

the room database problem has not recurred. Probably you have solved this problem！Thank you very much!
Will a new version be released to replace this version 3.3.5-beta2?

**Comment by sisier** [comment]
> @sisier #272 is the same error with `3.3.5-beta2`
> 
> > Thanks very much and I will do more test for this problem!
> 
> @4563599 What's your observation ?

No problem found at the moment, thank you 谢谢

**Comment by 4563599** [comment]
> > @sisier #272 is the same error with `3.3.5-beta2`
> > > Thanks very much and I will do more test for this problem!
> > 
> > 
> > @4563599 What's your observation ?
> 
> No problem found at the moment, thank you 谢谢

你是不是回复错了 你应该回复hannesa2   他解决的问题

**Comment by hannesa2** [comment]
Please try `3.3.5` if the errors still exists, please reopen this
