### ISSUE TITLE
why is android O devices needs to be set as foreground service?

### ISSUE THREAD

**Issue by Ganime422** [hannesa2/paho.mqtt.android#278]
Hello

I want to use this lib instead this one:
https://github.com/eclipse/paho.mqtt.android
because I had the `Targeting S+ (version 10000 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.` error.

In here I saw that it is needed to add this line for android O devices:
```
val client = MqttAndroidClient(context, uri, clientId).apply {
    setForegroundService(foregroundNotification, 3)
}
```

1. why is this needed? what is the foregraound service means and do I need to do any other refactroing to my code except for this?
2. what is the `foregroundNotification` variable? I don't use anything like it curently

thanks!

**Comment by hannesa2** [comment]
https://developer.android.com/about/versions/oreo/android-8.0-changes#back-all
https://developer.android.com/guide/components/foreground-services

You can give https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.4.0-beta7 a try. It's without foreground-services

**Comment by hannesa2** [comment]
https://github.com/eclipse/paho.mqtt.android/pull/418
https://github.com/eclipse/paho.mqtt.android/issues/274
https://github.com/eclipse/paho.mqtt.android/issues/195

**Comment by Ganime422** [comment]
I don't mind use it as a foregroun service if it's needed
but I currently don't know what to put inside this `foregroundNotification` since I don't use it in my app.
what should I put inside of it or can I just put `null`?

**Comment by hannesa2** [comment]
Please have a look in the code. It's a running sample
