### ISSUE TITLE
Can't include library in my project

### ISSUE THREAD

**Issue by mccuskk** [hannesa2/paho.mqtt.android#287]
Apologies for raising this here.

I am trying to add MQTT functionality to an existing app but can't for the life of me work out how to include this library. I'm using android studio bumblebee.

I've tried importing serviceLibrary but that doesn't work. I'm quite new to Android development (but not development) any help would be most appreciated.

Thanks

Kieran

**Comment by hannesa2** [comment]
Please see https://github.com/hannesa2/paho.mqtt.android#using-this-mqtt-android-client 
Are there some remaining open questions ?

**Comment by mccuskk** [comment]
Hi

Sorry but yes. What I want is the serviceLibrary added to my project. I
didn't know about jitpack but I now get that and I have the
org.eclipse.paho.client.mqttv3 external library in my project. What I would
like now is the serviceLibray. I've tried importing it but it fails. Any
help or pointers greatly appreciated.

Thanks

Kieran

**Comment by hannesa2** [comment]
> org.eclipse.paho.client.mqttv3 external library in my project. What I would like now is the serviceLibray. I've tried importing it but it fails

What are you doing ?
* Follow https://github.com/hannesa2/paho.mqtt.android#using-this-mqtt-android-client
* or share your project
