### ISSUE TITLE
Security Exception in A12

### ISSUE THREAD

**Issue by rohittayal96** [hannesa2/paho.mqtt.android#290]
Getting exception:
Fatal Exception: java.lang.SecurityException: Caller xxx needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.

on line 86 in `AlarmPingSender.kt`
```alarmManager.setExactAndAllowWhileIdle(AlarmManager.ELAPSED_REALTIME_WAKEUP, nextAlarmInMilliseconds, pendingIntent)```

Happens on A12 devices only if, Alarms & Reminders permission is turned off. Doc: [link](https://developer.android.com/training/scheduling/alarms#exact-permission-check)

**Comment by hannesa2** [comment]
https://github.com/hannesa2/paho.mqtt.android/blob/29ca7ac7503268c8086f8c0a4b3b3dc2f551f133/serviceLibrary/src/main/AndroidManifest.xml#L6

**Comment by rohittayal96** [comment]
@hannesa2 user can revoke the permission from app settings. You'll find "Alarms & reminders" option in App Info.

Please check "Check that your app still has permission" section of [this](https://developer.android.com/training/scheduling/alarms#exact-permission-check) doc.

**Comment by hannesa2** [comment]
This is a contribution open source project, and pull request are warmly welcome

**Comment by hannesa2** [comment]
Or maybe you give https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.4.0-beta7 a try. 
It's without this permission and prevent from too much wake up of the device. But needs some more tests

**Comment by rohittayal96** [comment]
Potential issue fixed with https://github.com/hannesa2/paho.mqtt.android/pull/159. Working fine on local testing, will update if production app stands to expectations.

**Comment by rohittayal96** [comment]
@hannesa2 After adopting this solution, MQTT has been disconnecting every 2 minutes for me. Checking further on what is actually resulting in issue.

**Comment by rohittayal96** [comment]
@hannesa2 let me know if this makes sense: https://github.com/hannesa2/paho.mqtt.android/pull/293
Meanwhile I am verifying my use-cases, and will update on it.

**Comment by hannesa2** [comment]
> After adopting this solution, MQTT has been disconnecting every 2 minutes for me

I probably understand why it's disconnecting every 2 minutes. Maybe a simple reconnect is the right solution. What's against this ?

**Comment by rohittayal96** [comment]
Earlier it was not disconnecting at all even when ideal for >30 minutes. Same behaviour now with handler-looper approach.

Why was it disconnecting?
Check starting two lines of PR description: https://github.com/hannesa2/paho.mqtt.android/pull/293

**Comment by hannesa2** [comment]
Maybe this will help ? https://github.com/hannesa2/paho.mqtt.android/issues/378#issuecomment-1288913139

**Comment by hannesa2** [comment]
Hopefully solved with https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.0 🤞
