### ISSUE TITLE
With 3.3.6: Unresolved reference: MqttAndroidClient

### ISSUE THREAD

**Issue by JorisBodin** [hannesa2/paho.mqtt.android#302]

**Comment by hannesa2** [comment]
These lines 
https://github.com/hannesa2/paho.mqtt.android/blob/master/serviceLibrary/build.gradle#L32-L33
are somehow ignored. That's new

**Comment by hannesa2** [comment]
https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.3.7
