### ISSUE TITLE
android.database.sqlite.SQLiteConnection.nativeExecute

### ISSUE THREAD

**Issue by lhj1079947827** [hannesa2/paho.mqtt.android#311]
I found this problem on my app
`1	android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
2	android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:556)
3	android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
4	android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
5	android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:551)
6	androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.java:94)
7	androidx.room.RoomDatabase.internalEndTransaction(RoomDatabase.java:594)
8	androidx.room.RoomDatabase.endTransaction(RoomDatabase.java:584)
9	info.mqtt.android.service.room.MqMessageDao_Impl.deleteId(MqMessageDao_Impl.java:212)
10	info.mqtt.android.service.room.MqMessageDatabase.discardArrived(MqMessageDatabase.kt:37)
11	info.mqtt.android.service.MqttService.acknowledgeMessageArrival(MqttService.kt:491)
12	info.mqtt.android.service.MqttAndroidClient.messageArrivedAction(MqttAndroidClient.kt:1066)
13	info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:887)
14	androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
15	androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
16	android.os.Handler.dispatchMessage(Handler.java:106)
17	android.os.Looper.loop(Looper.java:164)
18	android.app.ActivityThread.main(ActivityThread.java:6494)
19	java.lang.reflect.Method.invoke(Native Method)
20	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)`

**Comment by hannesa2** [comment]
In the past there was a similar error. Do you use most recent version ?

**Comment by lhj1079947827** [comment]
The version I am using now is 3.3.7 and the system version found is 8.0

**Comment by hannesa2** [comment]
I've no clue what's wrong here

    fun discardArrived(clientHandle: String, id: String): Boolean {
        return persistenceDao().deleteId(clientHandle, id) == 1
    }

Ok, I see the stacktrace, but what's the causing exception ? For me it looks like more an issue of Room itself and maybe a report to https://issuetracker.google.com makes sense

**Comment by lhj1079947827** [comment]
Okay, thanks

**Comment by hannesa2** [comment]
I close it, please reopen when you have more info
