### ISSUE TITLE
Invalid ClientHandle, IllegalArgumentException

### ISSUE THREAD

**Issue by YangShaoXiong** [hannesa2/paho.mqtt.android#318]
calling MqttAndroidClient.isConnected

**Comment by hannesa2** [comment]
Your write too much and please avoid too long explanation where and when it happens

**Comment by Elswah** [comment]
@hannesa2  this also happened with me when  call 
mQTTAndroidClient.disconnect(null, object : IMqttActionListener {
                override fun onSuccess(asyncActionToken: IMqttToken?) {
                    Log.d(TAG, "Disconnected")
                }

                override fun onFailure(asyncActionToken: IMqttToken?, exception: Throwable?) {
                    Log.d(TAG, "Failed to disconnect")
                }
            })

**Comment by Elswah** [comment]
@YangShaoXiong  did you solve it, please provide your solution

**Comment by hannesa2** [comment]
duplicate of #419
