### ISSUE TITLE
Unable to connect to server : ECONNREFUSED (Connection refused)

### ISSUE THREAD

**Issue by niaz-sagor** [hannesa2/paho.mqtt.android#319]
I was trying to run the basicSample project with the following server URI : tcp://0.0.0.0:1883. But it gives the following error

`Unable to connect to server token: Unable to connect to server (32103) - java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 1883) from /127.0.0.1 (port 46218) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused)`

Any idea why is this happening?

**Comment by hannesa2** [comment]
The basic sample is a only partial working left-over from upstream repo. Without looking in the code, the server is probably missing

**Comment by niaz-sagor** [comment]
> The basic sample is a only partial working left-over from upstream repo. Without looking in the code, the server is probably missing

yes. you are right. thank you for the reply.
