### ISSUE TITLE
MqttException on Android 12

### ISSUE THREAD

**Issue by Javatraher** [hannesa2/paho.mqtt.android#329]
Hello, I installed your library, a new error started popping up, here it is:

exception MqttException is never thrown in body of corresponding try statement

 There was no such problem before changing the library to yours, but I cannot refuse it, so it is necessary that the application works on android 12, so I ask you to help.

**Comment by Javatraher** [comment]
I'm glad I found the right place to ask a question) In general, I attached the usual connection code to the broker. 
       
        void connectToBroker() {
        String clientId = MqttClient.generateClientId();
        client = new MqttAndroidClient(this.getApplicationContext(), serverURL, clientId, Ack.AUTO_ACK);
        try {

            IMqttToken token = client.connect();
            token.setActionCallback(new IMqttActionListener() {
                @SuppressLint("SetTextI18n")
                @Override
                public void onSuccess(IMqttToken asyncActionToken) {
                    connectionStatus.setText("Connected To " + serverURL);
                    connectionFlag = true;
                    sendButton.setEnabled(true);
                    subscribeButton.setEnabled(true);

                }



                @Override
                public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                    Toast.makeText(getApplicationContext(), "Failed", Toast.LENGTH_SHORT).show();

                }

            });
        } catch (MqttException e) {
            e.printStackTrace();
        }
    }
An error with this text gives on the line with 

 } catch (MqttException e) {

**Comment by Javatraher** [comment]
Also, such an error pops up in the function that is responsible for sending the message and onDestroy, since there is also

} catch (MqttException e) {

**Comment by Javatraher** [comment]
Also attached a screenshot.

<img width="1671" alt="Снимок экрана 2022-06-28 в 17 40 57" src="https://user-images.githubusercontent.com/108346849/176234385-58b0104c-d517-4879-aa6c-9f1b2d464bfa.png">

**Comment by hannesa2** [comment]
Hmm, it's not always easy to understand the situation.
First, I understand it's not a runtime issue, it's a compile issue. Am I right ?
Second, the screenshot shows me you try to catch a never raised exception --> simply remove this part

Is it that easy ? When you show me your project, then I maybe understand better what's wrong.

**Comment by hannesa2** [comment]
There is no reason to `try..catch`. For this you have
`public void onFailure(IMqttToken asyncActionToken, Throwable exception) {`

It doesn't mean that the previous code was the best way. For me it's vice versa

**Comment by hannesa2** [comment]
> then I will reset the entire activity code for you, tell me how best? just code or insert document

Best is a pull request, or an own repo

**Comment by Javatraher** [comment]
Departing from the topic, this will be an application for a smart home in which commands are given to the device via the mqtt protocol. I add code where the usual connection, sending and receiving messages. This error is in all other parts of the application, but here is the least amount of code. I apologize in advance for so much of it, and for incorrectly inserted in some places, I'm new to github and don't know what to do with it
My MainActivity: 

 package com.example.serverconnectionukaa;

 import android.annotation.SuppressLint;
 import androidx.appcompat.app.ActionBar;
 import androidx.appcompat.app.AppCompatActivity;
 import android.os.Bundle;
 import android.view.View;
 import android.view.Window;
 import android.widget.Button;
 import android.widget.EditText;
 import android.widget.TextView;
 import android.widget.Toast;

 import org.eclipse.paho.client.mqttv3.IMqttActionListener;
 import org.eclipse.paho.client.mqttv3.IMqttDeliveryToken;
 import org.eclipse.paho.client.mqttv3.IMqttToken;
 import org.eclipse.paho.client.mqttv3.MqttCallback;
 import org.eclipse.paho.client.mqttv3.MqttClient;
 import org.eclipse.paho.client.mqttv3.MqttException;
 import org.eclipse.paho.client.mqttv3.MqttMessage;

import info.mqtt.android.service.Ack;
import info.mqtt.android.service.MqttAndroidClient;


import java.io.UnsupportedEncodingException;

public class    Main3Activity extends AppCompatActivity {

    EditText brokerAddress, textToSend, topicToSend, subscriptionTopic;
    Button connectButton, sendButton, subscribeButton;
    TextView receivedMessage, connectionStatus;

    MqttAndroidClient client;

    String serverURL = "tcp://broker.hivemq.com:1883";
    String topic = "mqtt/topic";
    String sTopic = "mqtt/sensorData";

    boolean connectionFlag = false;

    ////////////////////////////////////////////////////////////////////////////////////////////////
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Window w = getWindow();
        w.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);
        setContentView(R.layout.activity_main3);
        ActionBar actionBar = getSupportActionBar();

        /////////////////////////////////////////////////////////////////
        brokerAddress = findViewById(R.id.broker_address);
        textToSend = findViewById(R.id.text_to_send);
        topicToSend = findViewById(R.id.topic_to_send);
        subscriptionTopic = findViewById(R.id.subscription_topic);
        subscribeButton = findViewById(R.id.subscribe_button);
        connectButton = findViewById(R.id.connect_to_broker_button);
        sendButton = findViewById(R.id.send_button);
        receivedMessage = findViewById(R.id.received_message);
        connectionStatus = findViewById(R.id.connection_status);
        /////////////////////////////////////////////////////////////////
        connectButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                serverURL = "tcp://" + brokerAddress.getText().toString() + ":1883";
                connectToBroker();
            }
        });
        /////////////////////////////////////////////////////////////////
        sendButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                topic = topicToSend.getText().toString();
                sendMessage(topic);
            }
        });
        /////////////////////////////////////////////////////////////////
        subscribeButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                sTopic = subscriptionTopic.getText().toString();
                subscribeToTopic(sTopic);
            }
        });
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////
    void connectToBroker() {
        String clientId = MqttClient.generateClientId();
        client = new MqttAndroidClient(this.getApplicationContext(), serverURL, clientId, Ack.AUTO_ACK);

        try {

            IMqttToken token = client.connect();
            token.setActionCallback(new IMqttActionListener() {
                @SuppressLint("SetTextI18n")
                @Override
                public void onSuccess(IMqttToken asyncActionToken) {
                    connectionStatus.setText("Connected To " + serverURL);
                    connectionFlag = true;
                    sendButton.setEnabled(true);
                    subscribeButton.setEnabled(true);

                }



                @Override
                public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                    Toast.makeText(getApplicationContext(), "Failed", Toast.LENGTH_SHORT).show();

                }

            });
        } catch (MqttException e) {
            e.printStackTrace();
        }
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////
    void sendMessage(String topic) {
        String payload = textToSend.getText().toString();
        byte[] encodedPayload;
        try {
            encodedPayload = payload.getBytes("UTF-8");
            MqttMessage message = new MqttMessage(encodedPayload);
            client.publish(topic, message);
            Toast.makeText(getApplicationContext(), "Sent", Toast.LENGTH_SHORT).show();
        } catch (UnsupportedEncodingException | MqttException e) {
            e.printStackTrace();
        }
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////
    public void subscribeToTopic(String topic) {
        try {
            if (client.isConnected()) {
                client.subscribe(topic, 0);
                Toast.makeText(getApplicationContext(), "Subscribed", Toast.LENGTH_SHORT).show();
                client.setCallback(new MqttCallback() {
                    @SuppressLint("SetTextI18n")
                    @Override
                    public void connectionLost(Throwable cause) {
                        connectionStatus.setText("Connection Failed");
                        connectionFlag = false;
                    }

                    @Override
                    public void messageArrived(String topic, MqttMessage message) throws Exception {
                        receivedMessage.setText(message.toString());
                    }

                    @Override
                    public void deliveryComplete(IMqttDeliveryToken token) {
                    }
                });
            }
        } catch (Exception ignored) {
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (connectionFlag) {
            try {
                IMqttToken disconnectToken = client.disconnect();
                disconnectToken.setActionCallback(new IMqttActionListener() {
                    @Override
                    public void onSuccess(IMqttToken asyncActionToken) {
                        Toast.makeText(getApplicationContext(), "Disconnected", Toast.LENGTH_SHORT).show();
                        finish();
                    }

                    @Override
                    public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                        finish();
                    }
                });
            } catch (MqttException e) {
                e.printStackTrace();
            }
            connectionFlag = false;
        }
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////
}


My layout code:



 <?xml version="1.0" encoding="utf-8"?> 
 <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.serverconnectionukaa.Main3Activity">

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:paddingBottom="8dp">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="8dp"
                android:layout_marginRight="8dp"
                android:layout_marginTop="8dp"
                android:elevation="4dp"
                android:orientation="vertical"
                android:padding="8dp">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:fontFamily="sans-serif"
                    android:gravity="center"
                    android:text="@string/connect_to_mqtt"
                    android:textColor="#512da8"
                    android:textSize="24sp" />

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="@string/address"
                        android:textSize="16sp" />

                    <EditText
                        android:id="@+id/broker_address"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:inputType="text"
                        android:text="@string/broker_hivemq_com"
                        android:textColor="#424242"
                        tools:ignore="LabelFor" />

                </LinearLayout>

                <Button
                    android:id="@+id/connect_to_broker_button"
                    android:layout_width="match_parent"
                    android:layout_height="40dp"
                    android:background="#7B1FA2"
                    android:text="@string/connect"
                    android:textColor="#FFFFFF" />

                <TextView
                    android:id="@+id/connection_status"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:gravity="center"
                    android:text="@string/not_connected" />

            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="8dp"
                android:layout_marginRight="8dp"
                android:layout_marginTop="8dp"

                android:elevation="4dp"
                android:orientation="vertical"
                android:padding="8dp">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:fontFamily="sans-serif"
                    android:gravity="center"
                    android:text="@string/send_message_1"
                    android:textColor="#512da8"
                    android:textSize="24sp" />

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="@string/topic"
                        android:textSize="16sp" />

                    <EditText
                        android:id="@+id/topic_to_send"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:inputType="text"
                        android:text="@string/mqtt_topic"
                        android:textColor="#424242"
                        tools:ignore="LabelFor" />

                </LinearLayout>

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="@string/message"
                        android:textSize="16sp" />

                    <EditText
                        android:id="@+id/text_to_send"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:inputType="text"
                        android:text="@string/hi"
                        android:textColor="#424242"
                        tools:ignore="LabelFor" />
                </LinearLayout>

                <Button
                    android:id="@+id/send_button"
                    android:layout_width="match_parent"
                    android:layout_height="40dp"
                    android:background="#7B1FA2"
                    android:enabled="false"
                    android:text="@string/send"
                    android:textColor="#FFFFFF" />

            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginBottom="8dp"
                android:layout_marginLeft="8dp"
                android:layout_marginRight="8dp"
                android:layout_marginTop="8dp"

                android:elevation="4dp"
                android:orientation="vertical"
                android:padding="8dp">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:fontFamily="sans-serif"
                    android:gravity="center"
                    android:text="@string/incoming_messages"
                    android:textColor="#512da8"
                    android:textSize="24sp" />

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="@string/topic"
                        android:textSize="16sp" />

                    <EditText
                        android:id="@+id/subscription_topic"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:inputType="text"
                        android:text="@string/mqtt_sensordata"
                        android:textColor="#424242"
                        tools:ignore="LabelFor" />

                </LinearLayout>

                <Button
                    android:id="@+id/subscribe_button"
                    android:layout_width="match_parent"
                    android:layout_height="40dp"
                    android:background="#7B1FA2"
                    android:enabled="false"
                    android:text="@string/subscribe"
                    android:textColor="#FFFFFF" />

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="8dp"
                    android:gravity="center"
                    android:text="@string/received_message" />

                <TextView
                    android:id="@+id/received_message"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:fontFamily="sans-serif-thin"
                    android:gravity="center"
                    android:text="@string/nan"
                    android:textColor="#424242"
                    android:textSize="32sp" />

            </LinearLayout>

        </LinearLayout>

    </ScrollView>


</androidx.constraintlayout.widget.ConstraintLayout>


My gradle:

plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin'
    id 'com.android.application'
}

android {
    compileSdk 31

    defaultConfig {
        applicationId "com.example.serverconnectionukaa"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.4'
    implementation files('libs/serviceLibrary-release.aar')
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'


}


Second gradle:

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        jcenter()
    }
    repositories {
        maven {
            url "https://repo.eclipse.org/content/repositories/paho-releases/"
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.4"
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.10, 0.99.99]'
        classpath 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.4'
        classpath 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}



task clean(type: Delete) {
    delete rootProject.buildDir
}

My manifests:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.serverconnectionukaa">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />

    <application
        android:name=".ApplicationClass"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.Serverconnectionukaa"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity2"
            android:exported="false" />
        <activity
            android:name=".MainActivity6"
            android:exported="false" />
        <activity
            android:name=".Main5Activity"
            android:exported="false" />
        <activity
            android:name=".PopActivity"
            android:exported="false"
            android:theme="@style/Theme.Serverconnectionukaa.PopMe" />
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".Main2Activity" />
        <activity android:name=".MyNotificationActivity" />
        <activity android:name=".Main3Activity" />
        <activity android:name=".Main4Activity" />

        <service android:name="org.eclipse.paho.android.service.MqttService" />
    </application>

</manifest>

**Comment by hannesa2** [comment]
You have a running sample in this repository and (I guess) you have local issues, that's why you have to make it as easy as possible for me, to help you.
Sorry to say this, but now I should build up a running project with your snippets to figure out what wrong on your side ?  
No !

If you want, that I want to put afford into it, please make a pull request or a sample repository and show me the causing line and maybe a logcat dump. Otherwise please search someone else to help with your project.

**Comment by Javatraher** [comment]
I am extremely grateful that you decided to help me at all. I hope I did exactly what you needed, I'm so new to github that I don't even know how to ask the right question. here is the link to the repository:  https://github.com/Javatraher/serverconnectionukaa1

**Comment by hannesa2** [comment]
Please invite me as developer to be able to push there. Or maybe this is enough for you ?
<img width="693" alt="image" src="https://user-images.githubusercontent.com/3314607/176368886-d76fc0f6-aaac-4741-bfbc-5140128b628a.png">

**Comment by hannesa2** [comment]
> Second, the screenshot shows me you try to catch a never raised exception --> simply remove this part

I already wrote you this

**Comment by Javatraher** [comment]
> > Second, the screenshot shows me you try to catch a never raised exception --> simply remove this part
> 
> I already wrote you this

yes, but now the application crashes when I want to connect to the broker

**Comment by Javatraher** [comment]
Man i f&&&& love you
I had this one crash error: 

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.serverconnectionukaa, PID: 13894
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/Dispatchers;
        at info.mqtt.android.service.ping.AlarmPingSender$AlarmReceiver.onReceive(AlarmPingSender.kt:139)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1679)
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.Dispatchers" on path: DexPathList[[zip file "/data/app/~~eO2uwRcPCfM3m2KPCtuZSA==/com.example.serverconnectionukaa-A9c2WoUz4C_YQ2mMWywh3w==/base.apk"],nativeLibraryDirectories=[/data/app/~~eO2uwRcPCfM3m2KPCtuZSA==/com.example.serverconnectionukaa-A9c2WoUz4C_YQ2mMWywh3w==/lib/arm64, /data/app/~~eO2uwRcPCfM3m2KPCtuZSA==/com.example.serverconnectionukaa-A9c2WoUz4C_YQ2mMWywh3w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at info.mqtt.android.service.ping.AlarmPingSender$AlarmReceiver.onReceive(AlarmPingSender.kt:139) 
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1679) 
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 

i've googled it and implemented this 

implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.1.0'
implementation 'com.jakewharton.timber:timber:4.7.1'

And know it works

**Comment by hannesa2** [comment]
https://github.com/Javatraher/serverconnectionukaa1 works now

**Comment by BioEnable-bit** [comment]
@hannesa2 I have just compiled https://github.com/Javatraher/serverconnectionukaa1 and used our server URL but I am getting 
**onFailure: MqttException (0) - java.net.UnknownHostException: mqtt.googleapis.com** error

**Comment by hannesa2** [comment]
`UnknownHostException` means what it's called. -> the server is unknown. On my side it works

<img width="450" alt="image" src="https://user-images.githubusercontent.com/3314607/183620421-01f01512-53ae-4068-8486-9e8acbceda8d.png">

**Comment by BioEnable-bit** [comment]
**implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
implementation files('libs/serviceLibrary-release.aar')**


MqttAndroidClient client;
    
private static final String SERVER_URI = "ssl://mqtt.googleapis.com:8883";
 private static final String projectId = "XYZ";
private static final String cloudRegion = "XYZ";
private static final String registryId = "XYZ";
private String android_id;


android_id = Settings.Secure.getString(getContentResolver(),
                Settings.Secure.ANDROID_ID);
				
				
public void connectToBroker() {

        try {
            String clientId = "projects/" + projectId + "/locations/" + cloudRegion + "/registries/" + registryId + "/devices/" + android_id;
            
            client = new MqttAndroidClient(this, SERVER_URI, clientId, Ack.AUTO_ACK);
            IMqttToken token = client.connect();
            
            
            token.setActionCallback(new IMqttActionListener() {
                @Override
                public void onSuccess(IMqttToken asyncActionToken) {
                    Log.e("TAG", "onSuccess: "+asyncActionToken );
                 }
                @Override
                public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                    Toast.makeText(getApplicationContext(), "Failed", Toast.LENGTH_SHORT).show();
                    
                }
            });
        }
        catch (Exception e)
        {
            Log.e("TAG", "Exception: "+e );
         }
}

**Comment by BioEnable-bit** [comment]
I am getting an MQTT connection failed on Android 12. If I used the below dependencies 

 **implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
 implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'**

@hannesa2 If you have any samples available where MQTT connection on Android 12. Kindly share.

**Comment by hannesa2** [comment]
It's branch `master` with _extendenSample_ project

<img width="497" alt="image" src="https://user-images.githubusercontent.com/3314607/184596090-50a2c00d-a0f8-4ccb-9f79-1d547e218995.png">

<img width="521" alt="image" src="https://user-images.githubusercontent.com/3314607/184596225-ddc23cc4-c43e-4849-8046-0666c49e5fa0.png">

**Comment by sumitjoyride** [comment]
Hello  @hannesa2 
I am using
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.github.hannesa2:paho.mqtt.android:3.3.5'
    
    and i try to connect 
    Error:java.net.UnknownHostException  
    **in Android 12 and Android 14**
    Please Help us
    =====Code====
        fun connect(context: Context,onSuccess :()-> Unit,onError:(String)-> Unit) {
        this.context = context
        mqttClient = MqttAndroidClient(context, serverURI, ClientName, Ack.AUTO_ACK)

        mqttClient.setCallback(object : MqttCallback {
            override fun messageArrived(topic: String?, message: MqttMessage?) {
            }

            override fun connectionLost(cause: Throwable?) {
                Log.e(TAG, "Connection lost ${cause?.localizedMessage}")
            }

            override fun deliveryComplete(token: IMqttDeliveryToken?) {
                // Not used
            }
        })

        val options = MqttConnectOptions()
        try {
            mqttClient.connect(options, null, object : IMqttActionListener {
                override fun onSuccess(asyncActionToken: IMqttToken?) {
                    Log.e(TAG, "Connection success")
                    onSuccess()
                }

                override fun onFailure(asyncActionToken: IMqttToken?, exception: Throwable?) {
                    Log.e(TAG, "Connection failure")
                    Log.e(TAG, "onFailure::${exception?.localizedMessage}")
                    onError(exception?.message.toString())
                }
            })
        } catch (e: MqttException) {
            Log.e(TAG, "Failed to connect", e)
        }
    }

**Comment by hannesa2** [comment]
> java.net.UnknownHostException

Ii is what the name is: unknown host

**Comment by Jayden-ais** [comment]
@sumitjoyride how did you resolved  UnknownHostException  can you provide solution for this because i am facing same issue
