### ISSUE TITLE
Ability to construct MqttAndroidClient with specific MqttClientPersistence 

### ISSUE THREAD

**Issue by alabrecq** [hannesa2/paho.mqtt.android#333]
Hello, thank you for maintaining this library. I have a use case where I need to be able to specify MemoryPersistence on the MqttAndroidClient. In the old version of the Eclipse library this was a constructor parameter, but in the latest version of this library it is a private var and not possible to access. Without MemoryPersistence we run into an error after connecting to our server.

Do you think it would it be possible to move this property to a constructor parameter? It could still have a default value of null to utilize the behavior that exists in MqttConnection.kt, though it would be nice to be able to explicitly set MemoryPersistence (and maybe there are other use cases opened up by giving the client control over which class of persistence is used).

**Comment by hannesa2** [comment]
Or please point me to the old mechanism, to be sure to know, what you want

**Comment by alabrecq** [comment]
I added a PR that demonstrates what I was thinking of for this. Let me know what you think @hannesa2.

**Comment by hannesa2** [comment]
Here you go https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.4.0

**Comment by alabrecq** [comment]
Thank you!
