### ISSUE TITLE
org.eclipse.paho.client.mqttv3.internal.ClientState.getKeepAlive() on a null object reference

### ISSUE THREAD

**Issue by hoangchungk53qx1** [hannesa2/paho.mqtt.android#358]
![Screen Shot 2022-07-30 at 19 40 39](https://user-images.githubusercontent.com/52132635/181914709-ddf0d72a-36db-48b4-bdf6-462977c7d16f.png)

**Comment by hannesa2** [comment]
No clue about your implementation, but you miss call of [
override fun init(comms: ClientComms) ](https://github.com/hannesa2/paho.mqtt.android/blob/master/serviceLibrary/src/main/java/info/mqtt/android/service/ping/AlarmPingSender.kt#L47-L50)

**Comment by hoangchungk53qx1** [comment]
I implemented it like this

 ```
  fun connectMqttClient(
        context: Context,
        userId: String?,
        flexId: String? = ""
    ): Flow<Pair<Boolean, MqttAndroidClient>> = callbackFlow {
        mqttClient = MqttAndroidClient(
            context,
            BuildConfig.MQTT_DOMAIN,
            "android_${userId}_$deviceId${MqttClient.generateClientId()}"
        )
        mqttClient.setCallback(object : MqttCallback {
            override fun messageArrived(topic: String?, message: MqttMessage?) {
                Timber.tag(TAG).d("messageArrived  ${message.toString()}")
                busEvent(MessageMqtt(message = message.toString(), topic = topic))
            }

            override fun connectionLost(cause: Throwable?) {
                mqttClient.reconnect()
                Timber.tag(TAG).d("Connection lost ${cause.toString()}")
            }

            override fun deliveryComplete(token: IMqttDeliveryToken?) {

            }
        })
        val options = MqttConnectOptions()
        options.isAutomaticReconnect = true

        try {
            mqttClient.connect(options, null, object : IMqttActionListener {
                override fun onSuccess(asyncActionToken: IMqttToken?) {
                    trySend(Pair(true, mqttClient))
                }

                override fun onFailure(asyncActionToken: IMqttToken?, exception: Throwable?) {
                    trySend(Pair(false, mqttClient))
                }
            })
        } catch (e: MqttException) {
            e.printStackTrace()
        }
        awaitClose { mqttClient.connect() }
    }
```

**Comment by hannesa2** [comment]
This [extendedSample](https://github.com/hannesa2/paho.mqtt.android/tree/master/extendedSample) works properly, and maybe can be improved on several ways. But this is not the issue.

if _you_ have the _running_ code, it should not be very difficult, to debug _your_ code.
When you found an issue, please show me how to improve

**Comment by hannesa2** [comment]
Or you can make a pull request with your implementation and demonstrate what's going wrong. But with a code snippet alone, I will do nothing

**Comment by lotaviods** [comment]
Do you have any news? 
i'm facing the same issue.

**Comment by hannesa2** [comment]
The label `A sample is required` is still valid

**Comment by hannesa2** [comment]
Without running sample I close it. You can reopen it if you still need it

**Comment by kashyap-5paisa** [comment]
> No clue about your implementation, but you miss call of [ override fun init(comms: ClientComms) ](https://github.com/hannesa2/paho.mqtt.android/blob/master/serviceLibrary/src/main/java/info/mqtt/android/service/ping/AlarmPingSender.kt#L47-L50)

Can you please elaborate on "you missed call of init(comms)"? 
Were should we init it?

I tried reproducing it, but couldnt but we are getting crashlytics data hence trying to understand what might have gone wrong.
