### ISSUE TITLE
not using foreground service

### ISSUE THREAD

**Issue by Ganime422** [hannesa2/paho.mqtt.android#360]
Hi there
I just migrated to this lib and i have an android version 12, though I don't use this as a foreground service, meening I am not setting the client like this: client.setForegroundService(..)
and it looks like everything is working fine.

am i missing something? is it not mandatory to use it as a foreground service?

thanks

**Comment by hannesa2** [comment]
It will just not listen if you receive anything. Android will kill your service in the background after ~10 seconds.
You can give https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6.0-beta1 a try. There you should not use a foreground service.
