### ISSUE TITLE
Why aren't lower android versions supported? + Timber Error

### ISSUE THREAD

**Issue by Devenom1** [hannesa2/paho.mqtt.android#363]
I switched to this library to support Android 12+.

My app has minSDK 19 and targetSDK 21. This library has minSDK 21 so the Manifest merger fails when using it in my app.

To overcome this I manually edited the AndroidManifest.xml in this libraries aar file (locally).

I then got an error like `NoClassDef found` for Timber.
So I manually imported Timber using
`implementation 'com.jakewharton.timber:timber:5.0.1`

After this the library seems to work well on lower and higher android versions.

Is there any reason this library doesn't support lower android versions?

**Comment by hannesa2** [comment]
According https://apilevels.com/ it's just 1,2 %
Sorry, I save my time and prevent from using this old minSdk. If you want to change it, please open a pull request and I will merge it, if tests are running fine.

**Comment by Devenom1** [comment]
Quite a few users where we have the app launched actually depend on API 19+. Mqtt seems to be the best solution for these lower end devices as it is lightweight. I'll try to make a PR when I get time.
