### ISSUE TITLE
System App Error

### ISSUE THREAD

**Issue by Reginer** [hannesa2/paho.mqtt.android#371]
```
Sending non-protected broadcast MqttService.pingSender.*** from system uid 1000 pkg ***
java.lang.Throwable
at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:16116)
at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:16787)
at com.android.server.am.ActivityManagerService.broadcastIntentInPackage(ActivityManagerService.java:16989)
at com.android.server.am.ActivityManagerService$LocalService.broadcastIntentInPackage(ActivityManagerService.java:19650)
at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:442)
at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:285)
at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:5837)
at android.app.PendingIntent.sendAndReturnResult(PendingIntent.java:913)
at android.app.PendingIntent.send(PendingIntent.java:884)
at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:4796)
at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:3926)
at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:4175)
```

[Could you don't use AlarmManager?](https://github.com/hannesa2/paho.mqtt.android/blob/d8cb64a7eb5a95db6a79368743d00681c52bd36c/serviceLibrary/src/main/java/info/mqtt/android/service/ping/AlarmPingSender.kt#L53)

**Comment by hannesa2** [comment]
You could give https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6.0-beta1 a try 

it's without this receiver and forgeground service need.
https://github.com/hannesa2/paho.mqtt.android/blob/EnergySaving/serviceLibrary/src/main/java/info/mqtt/android/service/ping/AlarmPingSender.kt

If you do so, please give me feedback

**Comment by Reginer** [comment]
Worked well .

**Comment by Reginer** [comment]
It's minimum delay is 15 minutes?

**Comment by hannesa2** [comment]
> It's minimum delay is 15 minutes?

If you see an improvement, please tell it me.
Please give me feedback even after some time. I hesitate to merge it with feedback.

**Comment by Reginer** [comment]
[3.6.0-beta1](https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6.0-beta1) OK

**Comment by Reginer** [comment]
If possible, I hope to use other methods to replace the LocalBroadcastManager.
[androidx.localbroadcastmanager is being deprecated](https://developer.android.com/jetpack/androidx/releases/localbroadcastmanager)

**Comment by Reginer** [comment]
Exception occurs after using WorkManager.

https://issuetracker.google.com/issues/170228126

**Comment by hannesa2** [comment]
Thank you to point this out. With https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6.0-beta2 you'll see a Room update to `2.4.3`. I'm not sure if it helps.

I tried [WorkManager 28](https://developer.android.com/jetpack/androidx/releases/work#version_28_2) but here I run into non-understood compile errors, that's why I keep on [WorkManager 27](https://developer.android.com/jetpack/androidx/releases/work#version_27_2)

**Comment by Reginer** [comment]
`android.database.CursorWindowAllocationException`
The problem still exists.
It may be a problem with the ROOM.

**Comment by hannesa2** [comment]
> `android.database.CursorWindowAllocationException` The problem still exists. It may be a problem with the ROOM.

For me it looks like a memory issue. But who knows ?

Maybe this will help ? https://github.com/hannesa2/paho.mqtt.android/issues/378#issuecomment-1288913139

**Comment by Reginer** [comment]
```
E AndroidRuntime: Caused by: java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: 1000, callingPackage: android
E AndroidRuntime: 	at com.android.server.AlarmManagerService.setImpl(AlarmManagerService.java:1824)
E AndroidRuntime: 	at com.android.server.AlarmManagerService$4.set(AlarmManagerService.java:2181)
E AndroidRuntime: 	at android.app.AlarmManager.setImpl(AlarmManager.java:705)
E AndroidRuntime: 	at android.app.AlarmManager.set(AlarmManager.java:644)
E AndroidRuntime: 	at com.android.server.job.controllers.TimeController.updateAlarmWithListenerLocked(TimeController.java:419)
E AndroidRuntime: 	at com.android.server.job.controllers.TimeController.setDelayExpiredAlarmLocked(TimeController.java:387)
E AndroidRuntime: 	at com.android.server.job.controllers.TimeController.checkExpiredDelaysAndResetAlarm(TimeController.java:333)
E AndroidRuntime: 	at com.android.server.job.controllers.TimeController.reevaluateStateLocked(TimeController.java:207)
E AndroidRuntime: 	at com.android.server.job.JobSchedulerService$3.onReceive(JobSchedulerService.java:864)
E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1574)
```
It may be a problem with WorkManager.

**Comment by hannesa2** [comment]
@Reginer Which version do you use ? 
The latest [3.6.0-beta4](https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6.0-beta4) uses the [latest](https://github.com/hannesa2/paho.mqtt.android/pull/393/files) WorkManager and latest room, which is the next hope that Google solved this issue

**Comment by Reginer** [comment]
This problem has been modified in the new version of the AOSP source code. 
WorkManager does not know whether it has been handled.
I will update to 3.6.0-beta4, it is not easy to reproduce.

**Comment by hannesa2** [comment]
Now `3.6.0-beta6` is out now https://github.com/hannesa2/paho.mqtt.android/issues/411#issuecomment-1419467533
I close this, but if it still exists, please reopen it again
