### ISSUE TITLE
I used version 3.4.0 and running on android 12 with error as described

### ISSUE THREAD

**Issue by hoangchungk53qx1** [hannesa2/paho.mqtt.android#378]
![Screen Shot 2022-10-24 at 11 47 05](https://user-images.githubusercontent.com/52132635/197450363-71483ab5-7981-4c4b-8dbb-3e938f68e99f.png)

**Comment by hannesa2** [comment]
It's a leftover from [eclipse way](https://github.com/eclipse/paho.mqtt.android) and normally it's not an error, just a please-avoid-issue.

First, please use a more recent version.
Second, you can give https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6.0-beta2 a try. It uses Workmanager and don't need foreground service and should remove your described issue. 
If you use 3.6.0-beta2, please give me a feedback, because I hesitate to merge it.

**Comment by hoangchungk53qx1** [comment]
I just tested version 3.6.0-beta2 . found it working fine. you can check more and release this version. thanks a lot

**Comment by hannesa2** [comment]
Sure, I collect feedback and this is the pull request for it https://github.com/hannesa2/paho.mqtt.android/pull/159

The only thing which let's me hesitate is https://github.com/hannesa2/paho.mqtt.android/issues/230 I was not able to reproduce it on my side. But the bad feeling left.

Maybe you test `3.6.0-beta2` for a longer period and give me fedback again in a few days/weeks/months ?

**Comment by hoangchungk53qx1** [comment]
@hannesa2  I found the answer here https://stackoverflow.com/questions/60205993/what-does-workmanager-do-with-jobs-after-hitting-jobscheduler-limit-of-100 and here https://github.com/googlecodelabs/android-workmanager/issues/16

You can refer to it, I think if the jobCount exceeds 100, cancel the job to avoid crashing the app
I will spend time this week testing more version 3.6.0-beta2

**Comment by hannesa2** [comment]
I'm not sure how to handle it on the right way. The issues are from 2018. 
I made an attempt to get rid of it with 7cc01766 and a new version https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6.0-beta3 (it's done in a few minutes)

Btw, when you see a proper solution, please make a pull request targeting to https://github.com/hannesa2/paho.mqtt.android/pull/159

**Comment by hoangchungk53qx1** [comment]
hi @hannesa2 . I tested and found that version 3.4.0 reconnect still works fine when hiding the app and reopening it. and version 3.6.0-beta2 does not work when hiding the app and reopening it for a period of 30 minutes. it throw Connection lost (32109) - java.io.EOFException

**Comment by hannesa2** [comment]
Did you observe this topic with `3.6.0-beta6` as well ?

**Comment by hoangchungk53qx1** [comment]
Hi @hannesa2 . version 3.4.0 is still the best working version, it can automatically reconnect when the network is lost, and version 3.60 cannot automatically connect when the network is lost.

**Comment by hannesa2** [comment]
Hopefully solved with https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.0 🤞
