### ISSUE TITLE
Invalid ClientHandle, IllegalArgumentException

### ISSUE THREAD

**Issue by Elswah** [hannesa2/paho.mqtt.android#419]
this exception happened to me when calling 

  ```
mQTTAndroidClient.disconnect(null, object : IMqttActionListener {
                override fun onSuccess(asyncActionToken: IMqttToken?) {
                    Log.d(TAG, "Disconnected")
                }

                override fun onFailure(asyncActionToken: IMqttToken?, exception: Throwable?) {
                    Log.d(TAG, "Failed to disconnect")
                }
            })
```

and the application getting crashed
- I use MQTT as singelton class

**Comment by Elswah** [comment]
i call this method to close the connection
  
```
fun destroy() {
        try {

            mQTTAndroidClient.close()
            mQTTAndroidClient.unregisterResources()
            disconnect()
        }catch (e:Exception){

        }
    }
```
 ```
private fun disconnect() {
        try {
            ioScope.launch {
                mQTTAndroidClient.disconnect(null, object : IMqttActionListener {
                    override fun onSuccess(asyncActionToken: IMqttToken?) {
                        Log.d(TAG, "Disconnected")
                    }

                    override fun onFailure(asyncActionToken: IMqttToken?, exception: Throwable?) {
                        Log.d(TAG, "Failed to disconnect")
                    }
                })
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
```

**Comment by hannesa2** [comment]
@Elswah Thank you for the sample. I investigated in extended sample app and found some issues in sample #421 

Your described issue needs some debug and I want to avoid to debug foreign (incomplete) code snippets. 
It would be super helpful if you could demonstrate the issue in extended sample, best as Espresso test. 

I [added an disconnect test](https://github.com/hannesa2/paho.mqtt.android/pull/421/files#diff-0a39f4f06f9f93e347f2c1d4ff1075d2c8d6725fc276fc7c9f18b901c6f70be6) as well to have a base ground doing this

**Comment by hannesa2** [comment]
Without running sample I close it. You can reopen it if you still need it

**Comment by hannesa2** [comment]
Please see https://github.com/hannesa2/paho.mqtt.android/pull/608

**Comment by 5672875** [comment]
I'm encountering the following exception in the below block of code while trying to disconnect and clean up the MQTT client:

Exception:    java.lang.IllegalArgumentException: Invalid ClientHandle

Code where this exception occurring:  
if (mqttClient != null) {
    try {
        ALLogger.debug(LOG_TAG, "Mqtt broker creating new client. client connection status " + mqttClient.isConnected());
        mqttClient.disconnect();
        mqttClient.unregisterResources();
        //mqttClient.close();
        mqttClient = null;
    } catch (Exception ex) {
        ALLogger.error(LOG_TAG, "Start Connection exception " + ex.getMessage());
    }
}

And the application getting crashed.

**Comment by hannesa2** [comment]
Which version do you use ?

**Comment by hannesa2** [comment]
The purpose of a release with a changelog is to have a chance to investigate, when the above linked #608 was released.
In the release 4.3 it's included

**Comment by hannesa2** [comment]
My suggestion:
* use formatted code snipped and mark it as code (I did it partially for you)
* use moste recent version
