### ISSUE TITLE
run only in service 

### ISSUE THREAD

**Issue by AttITuder** [hannesa2/paho.mqtt.android#431]
D  [:0, ]:Connection lost 已断开连接 (32109) - java.net.SocketException: Software caused connection abort

**Comment by hannesa2** [comment]
too less information

**Comment by maksood5010** [comment]
Mine Was working fine then i have changed some code then  I Also Got this error this is my logcat

Connection lost Connection lost (32109) - java.net.SocketException: Software caused connection abort
Read error: ssl=0xb40000796559e558: I/O error during system call, Software caused connection abort
Write error: ssl=0xb4000079655a3358: I/O error during system call, Broken pipe
SSL shutdown failed: ssl=0xb4000079655a3358: I/O error during system call, Success

Connection failure: Client is connected (32100) @hannesa2
