### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method long org.eclipse.paho.client.mqttv3.internal.ClientState.getKeepAlive()

### ISSUE THREAD

**Issue by dzboy** [hannesa2/paho.mqtt.android#433]
1902-27 14:12:51.600 4378 5096 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'long org.eclipse.paho.client.mqttv3.internal.ClientState.getKeepAlive()' on a null object reference
--
2002-27 14:12:51.600 4378 5096 E AndroidRuntime: at org.eclipse.paho.client.mqttv3.internal.ClientComms.getKeepAlive(ClientComms.java:1)
2102-27 14:12:51.600 4378 5096 E AndroidRuntime: at info.mqtt.android.service.ping.AlarmPingSender.start(AlarmPingSender.kt:5)
2202-27 14:12:51.600 4378 5096 E AndroidRuntime: at org.eclipse.paho.client.mqttv3.internal.ClientState.connected(ClientState.java:3)
2302-27 14:12:51.600 4378 5096 E AndroidRuntime: at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:31)
2402-27 14:12:51.600 4378 5096 E AndroidRuntime: at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:22)
2502-27 14:12:51.600 4378 5096 E AndroidRuntime: at java.lang.Thread.run(Thread.java:922)

plz check AlarmPingSender：

```kotlin
override fun start() {
        // ...
        schedule(clientComms!!.keepAlive)
        // ...
}
```

**Comment by hannesa2** [comment]
Duplicate of https://github.com/hannesa2/paho.mqtt.android/issues/358

**Comment by hannesa2** [comment]
Without running sample I close it. You can reopen it if you still need it

**Comment by jxtx123456** [comment]
![image](https://github.com/hannesa2/paho.mqtt.android/assets/10148767/1f6e13e2-da48-4a8a-b945-3cc10ac2f541)
version：4.2
When will it be resolved?

**Comment by jxtx123456** [comment]
> Without running sample I close it. You can reopen it if you still need it

![image](https://github.com/hannesa2/paho.mqtt.android/assets/10148767/1f6e13e2-da48-4a8a-b945-3cc10ac2f541)
version：4.2
I also encountered，When will it be resolved?

**Comment by hannesa2** [comment]
> When will it be resolved?

It's faster when you help me, to reproduce the error. I never run into this.
Looks lie the `init()` was not called 
![image](https://github.com/hannesa2/paho.mqtt.android/assets/3314607/48ef6f6d-645c-4d49-841e-da68b5c75e46)

**Comment by kashyap-5paisa** [comment]
Can you please elaborate on "init"? Were should we init it?

I tried reproducing it, but couldnt but we are getting too many crashlytics data hence trying to understand what might have gone wrong.

**Comment by kashyap-5paisa** [comment]
@FJEagle Thank you for crash fix, but how to actually fix this @dzboy @hannesa2 @jxtx123456 ANYONE?? 
What are we doing wrongg?

**Comment by hannesa2** [comment]
This is still valid https://github.com/hannesa2/paho.mqtt.android/issues/433#issuecomment-1951990814
I've to reproduce it

**Comment by hannesa2** [comment]
Please use `implementation("com.github.hannesa2:paho.mqtt.android:4.6-beta1")` and give me feedback.
I will not merge https://github.com/hannesa2/paho.mqtt.android/pull/927 without feedback.
@dzboy 
@kashyap-5paisa 
@jxtx123456
