### ISSUE TITLE
Cannot perform this operation because the connection pool has been closed

### ISSUE THREAD

**Issue by liuhuan0225** [hannesa2/paho.mqtt.android#438]
Cannot perform this operation because the connection pool has been closed.printStackTrace{"detailMessage":"Cannot perform this operation because the connection pool has been closed.","stackTrace":[{"declaringClass":"android.database.sqlite.SQLiteConnectionPool","fileName":"SQLiteConnectionPool.java","lineNumber":962,"methodName":"throwIfClosedLocked"},{"declaringClass":"android.database.sqlite.SQLiteConnectionPool","fileName":"SQLiteConnectionPool.java","lineNumber":599,"methodName":"waitForConnection"},{"declaringClass":"android.database.sqlite.SQLiteConnectionPool","fileName":"SQLiteConnectionPool.java","lineNumber":348,"methodName":"acquireConnection"},{"declaringClass":"android.database.sqlite.SQLiteSession","fileName":"SQLiteSession.java","lineNumber":894,"methodName":"acquireConnection"},{"declaringClass":"android.database.sqlite.SQLiteSession","fileName":"SQLiteSession.java","lineNumber":752,"methodName":"executeForChangedRowCount"},{"declaringClass":"android.database.sqlite.SQLiteStatement","fileName":"SQLiteStatement.java","lineNumber":64,"methodName":"executeUpdateDelete"},{"declaringClass":"androidx.sqlite.db.framework.FrameworkSQLiteStatement","fileName":"FrameworkSQLiteStatement.kt","lineNumber":38,"methodName":"executeUpdateDelete"},{"declaringClass":"info.mqtt.android.service.room.MqMessageDao_Impl","fileName":"MqMessageDao_Impl.java","lineNumber":208,"methodName":"deleteId"},{"declaringClass":"info.mqtt.android.service.room.MqMessageDatabase$discardArrived$1$queue$1","fileName":"MqMessageDatabase.kt","lineNumber":46,"methodName":"invokeSuspend"},{"declaringClass":"kotlin.coroutines.jvm.internal.BaseContinuationImpl","fileName":"ContinuationImpl.kt","lineNumber":33,"methodName":"resumeWith"},{"declaringClass":"kotlinx.coroutines.DispatchedTask","fileName":"DispatchedTask.kt","lineNumber":106,"methodName":"run"},{"declaringClass":"kotlinx.coroutines.internal.LimitedDispatcher","fileName":"LimitedDispatcher.kt","lineNumber":42,"methodName":"run"},{"declaringClass":"kotlinx.coroutines.scheduling.TaskImpl","fileName":"Tasks.kt","lineNumber":95,"methodName":"run"},{"declaringClass":"kotlinx.coroutines.scheduling.CoroutineScheduler","fileName":"CoroutineScheduler.kt","lineNumber":570,"methodName":"runSafely"},{"declaringClass":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker","fileName":"CoroutineScheduler.kt","lineNumber":750,"methodName":"executeTask"},{"declaringClass":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker","fileName":"CoroutineScheduler.kt","lineNumber":677,"methodName":"runWorker"},{"declaringClass":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker","fileName":"CoroutineScheduler.kt","lineNumber":664,"methodName":"run"}],"suppressedExceptions":[{"stackTrace":[],"suppressedExceptions":[]}]}

**Comment by hannesa2** [comment]
Which version do you use ? Btw, formatting the call stack is no mistake

**Comment by hannesa2** [comment]
Please give https://github.com/hannesa2/paho.mqtt.android/tree/master/extendedSample a try
