### ISSUE TITLE
Android 14 support 

### ISSUE THREAD

**Issue by cyn-ph** [hannesa2/paho.mqtt.android#473]
Hi! MQTT Android Service is adding the `android.permission.SCHEDULE_EXACT_ALARM` permission to the merged manifest, with the upcoming Android 14 changes on [exact alarms](https://developer.android.com/about/versions/14/changes/schedule-exact-alarms) the permission is being denied by default, will there be any updates to the library that we need to watch for?

Thanks!

**Comment by hannesa2** [comment]
Please try https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.0-beta2 is comes without this permission and should help to save energy because now Android controls/orchestrate when the device awakes or not.

Unfortunately, no feedback reaches me, if the 4.0 works like a charm or causes issues, so I hesitate to merge https://github.com/hannesa2/paho.mqtt.android/pull/430

But if you need  Android 14 support, I'm happy to approve/merge a pull request

**Comment by alessioemireni** [comment]
Hi @hannesa2 I'm testing the 4.0 beta2. I will inform you if something is not working. Thx

**Comment by masanori-taniguchi** [comment]
I tried 4.0 beta2 on Android 14 and it is crashing with the following error in MqttAndroidClient's registReceiver

One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

**Comment by hannesa2** [comment]
I see https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported

**Comment by hannesa2** [comment]
I started a api34 device and run ExtendedSample, but I don't see the issue.
What I've to do, to run into it ?

**Comment by alessioemireni** [comment]
@hannesa2 I think you have to target the project to API Level 14 per documentation.

**Comment by alessioemireni** [comment]
Hi @hannesa2 we have tested with success the 4.0-beta2 version library neither in foreground nor in background and it works like a charm!
Any chance to release a 4.0 stable version? Or do you want to fix the Android 14 crash?

**Comment by hannesa2** [comment]
Thank you !
As I understand you recommend to merge it. 👍 I hope you'll not change your opinion. If you find something, please don't hesitate to open an issue. Please keep on testing on this. In the past some errors raise on long run of an app. Look for issues with label 
![image](https://github.com/hannesa2/paho.mqtt.android/assets/3314607/43d5d7cf-7925-464c-abd5-7e95917a2e66)


I guess it makes sense to split Android14 as an additional pull request . At least I started unsuccessfully to test with api34 https://github.com/hannesa2/paho.mqtt.android/pull/477

**Comment by hannesa2** [comment]
> @hannesa2 I think you have to target the project to API Level 34 per documentation.

Ok, I guess I did it https://github.com/hannesa2/paho.mqtt.android/pull/480 but I see no error

**Comment by hannesa2** [comment]
> > @hannesa2 I think you have to target the project to API Level 34 per documentation.
> 
> Ok, I guess I did it #480 but I see no error. Please ping me to the necessary change

I found it https://github.com/hannesa2/paho.mqtt.android/actions/runs/5596406823/jobs/10260179516?pr=477

**Comment by hannesa2** [comment]
Sure, first to reproduce the issue. Btw, anyone is warmly welcome to contribute

**Comment by alessioemireni** [comment]
> Thank you ! As I understand you recommend to merge it. 👍 I hope you'll not change your opinion. If you find something, please don't hesitate to open an issue. Please keep on testing on this. In the past some errors raise on long run of an app. Look for issues with label ![image](https://user-images.githubusercontent.com/3314607/254801365-43d5d7cf-7925-464c-abd5-7e95917a2e66.png)
> 
> I guess it makes sense to split Android14 as an additional pull request . At least I started unsuccessfully to test with api34 #477 and here is the Android 14 pull request #480

For me it's ok. We can merge it

**Comment by hannesa2** [comment]
I can/could merge https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.0-beta2 (corresponding PR https://github.com/hannesa2/paho.mqtt.android/pull/430)

But this Android 14 makes me headache. After fixing compile issues, runtime issues and permissions, the Espresso tests are failing. 
It looks like there is something with the connection.

Currently, his comes not with a high priority for me. If you want that it's solved soon, I invite you, the help me to investigate/solve it

**Comment by cyn-ph** [comment]
Hi @hannesa2, I just wanted to let you know that we have successfully tested and updated to 4.0-beta2 version of the library. I will keep monitoring and open an issue if something comes up! 

About this comment:

> Thank you !
As I understand you recommend to merge it. 👍 I hope you'll not change your opinion. If you find something, please don't hesitate to open an issue. Please keep on testing on this. In the past some errors raise on long run of an app. Look for issues with label
image
I guess it makes sense to split Android14 as an additional pull request . At least I started unsuccessfully to test with api34 https://github.com/hannesa2/paho.mqtt.android/pull/477 and here is the Android 14 pull request https://github.com/hannesa2/paho.mqtt.android/pull/480

I agree that would be ideal to split Android14 support as an aditional PR, maybe after stable release of 4.0?

Thanks again!

**Comment by hannesa2** [comment]
>  I will keep monitoring and open an issue if something comes up!

yes please

It's just number cosmetic, here is the stable https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.0

**Comment by vicktor** [comment]
i fixed  RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED error

in AlarmPingSender.java

```
public void start() {
		String action = MqttServiceConstants.PING_SENDER
				+ comms.getClient().getClientId();
		Log.d(TAG, "Register alarmreceiver to MqttService"+ action);
		service.registerReceiver(alarmReceiver, new IntentFilter(action), Context.RECEIVER_EXPORTED);

		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
			pendingIntent = PendingIntent.getBroadcast(service, 0, new Intent(
					action), PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
		} else {
			pendingIntent = PendingIntent.getBroadcast(service, 0, new Intent(
					action), PendingIntent.FLAG_UPDATE_CURRENT);
		}

		schedule(comms.getKeepAlive());
		hasStarted = true;
	}
```

**Comment by dtrognn** [comment]
Hi @hannesa2, I am also encountering an issue related to the SCHEDULE_EXACT_ALARM permission. I tried updating to newer versions (3.6.2 - 3.6.4 - 4.3.beta3), but it reported the following error:

Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

Does this mean I have to downgrade the Kotlin version?

**Comment by hannesa2** [comment]
@dtrognn Here https://github.com/hannesa2/paho.mqtt.android/pull/658 I demonstrate the usage as jitpack artifact.
There is no need to downgrade Kotlin. On the first view, it looks like an issue on your side

**Comment by hackaprende** [comment]
How can I use the version with those changes? Or how can I edit the AlarmPingSender.java file?

> i fixed RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED error
> 
> in AlarmPingSender.java
> 
> ```
> public void start() {
> 		String action = MqttServiceConstants.PING_SENDER
> 				+ comms.getClient().getClientId();
> 		Log.d(TAG, "Register alarmreceiver to MqttService"+ action);
> 		service.registerReceiver(alarmReceiver, new IntentFilter(action), Context.RECEIVER_EXPORTED);
> 
> 		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
> 			pendingIntent = PendingIntent.getBroadcast(service, 0, new Intent(
> 					action), PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
> 		} else {
> 			pendingIntent = PendingIntent.getBroadcast(service, 0, new Intent(
> 					action), PendingIntent.FLAG_UPDATE_CURRENT);
> 		}
> 
> 		schedule(comms.getKeepAlive());
> 		hasStarted = true;
> 	}
> ```

**Comment by hannesa2** [comment]
There is a running pull request. What else is needed ?
Give me a running sample as a repository and I can help you.
