### ISSUE TITLE
Too many bind requests(999+) for service Intent { cmp={myPkg}/info.mqtt.android.service.MqttService }

### ISSUE THREAD

**Issue by FJEagle** [hannesa2/paho.mqtt.android#479]
lib ver: 3.5.1

My app failed to connect to mqtt server with error log printed: Too many bind requests(999+) for service Intent { cmp={myPkg}/info.mqtt.android.service.MqttService }

It happened only when my app had run on SamSung phone (SM-N9860) for some days. 
Other brand phones, like xiaomi/vivo/oppo/huawei, don't have this problem.

I'm not sure whether this problem is a bug of the lib or because of my incorrect usage of the lib. 

Any suggestion would be appreciated.

**Comment by hannesa2** [comment]
When it only happens on a Samsung ... probably there is the issue ?
Please give https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.0 a try and reopen, when it raise again
