### ISSUE TITLE
When the application is not used in the background, I get the error of falling into disconnect after a certain period of time 

### ISSUE THREAD

**Issue by gelbertgel** [hannesa2/paho.mqtt.android#497]
## Bug Report
No error is received when the device is actively used, disconnect error is received when the screen is locked or the device is not used for a certain period of time.

## Screenshot:
![Screenshot_20230807-164131_MQTT Example](https://github.com/hannesa2/paho.mqtt.android/assets/31124402/3157e8bd-046f-44f6-8856-fc271fa04887)

## How To Reproduce

1. The phone is connected to the Internet.
2. The phone connects to the mqtt server successfully.
3. The screen is locked or the device is not used for a certain period of time.
4. After a certain time, the mqtt connection is closed.
5. Reconnect mqtt server

### Code sample

```
mqttAndroidClient = MqttAndroidClient(applicationContext, serverUri, clientId)
        mqttAndroidClient.setCallback(object : MqttCallbackExtended {
            override fun connectComplete(reconnect: Boolean, serverURI: String) {
          
            }

            override fun connectionLost(cause: Throwable?) {
                addToHistory("The Connection was lost.")
            }

            override fun messageArrived(topic: String, message: MqttMessage) {
                addToHistory("Incoming message: " + String(message.payload))
            }

            override fun deliveryComplete(token: IMqttDeliveryToken) {}
        })
```

**Log:**

The Connection was lost.

### Environment

What version of this client are you using? Android 9,10,11,12,13 -> All android devices
Which MQTT broker (name and version)? Mosquitto v2.0.15

**Comment by hannesa2** [comment]
Which version of this library do you use ?

**Comment by gelbertgel** [comment]
I used v4.0

**Comment by gelbertgel** [comment]
Please help me. I'm trying to get the project up to my deadline. I need to settle this matter before my boss gets angry :D

**Comment by hannesa2** [comment]
For me this is a normal behavior and a feature ! 
The library `4.x` use `WorkMananger` which prevent from use of a foreground service. This helps to save battery. The system kills your app on background use or when device is locked. So you loose the connection. The `WorkMananger` awake on a battery save mechanism on a period time and needs to connect again, check on new messages, after system fall to sleep again .....

If you want to have your device always on and waste battery please use `3.x `
