### ISSUE TITLE
Unresolved reference: MqttAndroidClient

### ISSUE THREAD

**Issue by sheng930920** [hannesa2/paho.mqtt.android#499]
In App Gradle

```java
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'com.github.hannesa2:paho.mqtt.android:4.1'
```
app run error

```java
e: file:///Users/liqisheng/Project/Android/MobileNest/app/src/main/java/com/shd/nest/mqtt/MqttClientManager.kt:20:34 Unresolved reference: MqttAndroidClient
```

<img width="839" alt="image" src="https://github.com/hannesa2/paho.mqtt.android/assets/13199067/1d9e0827-f158-4336-b9bc-496806bf7f74">

**Comment by sheng930920** [comment]
Reduce the version to 3.3.7 The project build works normally, and the project build error with the latest version

**Comment by hannesa2** [comment]
For me 4.1 works properly, maybe you miss the jitpack.io setup ?
https://github.com/hannesa2/paho.mqtt.android#using-this-mqtt-android-client

**Comment by sheng930920** [comment]
An error occurred when compiling and running the project using the 4.1 version of the dependency library Android Studio，The following is the configuration of the project build.gradle file

```java
buildscript {
    ext.kotlin_version = '1.8.0'
    ext.androidXCore = "1.6.0"
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
<img width="1423" alt="image" src="https://github.com/hannesa2/paho.mqtt.android/assets/13199067/6728856c-3732-44e9-83e5-7d9ba495b23b">

**Comment by hannesa2** [comment]
Sorry, with the snippets I can't do nothing. Only running code demonstrate the real issue. 

To demonstrate what's a running code, I made #501 
Here you can verify/investigate why it's working and why it's not working on your side. For me the source is somewhere located on your side.
