### ISSUE TITLE
Unable to populate MQTT data to RecyclerView

### ISSUE THREAD

**Issue by AlfaBravoX** [hannesa2/paho.mqtt.android#506]
I assume this is async MQTT client correct ? I have problem to populate JSON formatted array filled by json objects received over MQTT to UI in RecyclerView.

RecyclerView uses MQTT data set gained at `messageArrived()` then JSON is passed to `RecyclerView` adapter and then `notifyDataSetChanged()` is called.

UI does not show any items in RecyclerView activity until app is put to background and foreground. After that items are populated on UI screen. 

I have in the logs `android.view.ViewRootImpl$CalledFromWrongThreadException: Only
                                                                                                    the original thread that created a view hierarchy can touch
                                                                                                    its views.`

so I tried update dataset in Runnable() like this:

```
getActivity().runOnUiThread(new Runnable() {
    @Override
    public void run() {
        //...
        myJsonArray.add( myJSONobject );
        myAdapter.notifyDataSetChanged();
        }   
    });
```

however there is no change.

Any ideas would be highly appreciated as I am running out of ideas.

thanks!

**Comment by hannesa2** [comment]
You receive `myJSONobject` correct and can log it ?
If yes, the issue is somewhere located in your code -sorry-

**Comment by AlfaBravoX** [comment]
Ok, thanks for feedback I will try to modify code to process UI changes with
`mHandler = new Handler(Looper.getMainLooper());` approach

**Comment by hannesa2** [comment]
Your attempt looks promising, and I close this in the meanwhile. 
if you thing it's still related to this lib, please reopen it again
