### ISSUE TITLE
why MqttAndroidClient.reconnect() is Unit ?

### ISSUE THREAD

**Issue by zhouzidan** [hannesa2/paho.mqtt.android#513]
Hi, I have a question
I found that the MqttAndroidClient.reconnect() method is empty. 
I want to know why this method is empty? Based on what considerations?

`    
@Throws(MqttException::class) 
override fun reconnect() = Unit
`

**Comment by hannesa2** [comment]
> Hi, I have a question I found that the MqttAndroidClient.reconnect() method is empty. I want to know why this method is empty? Based on what considerations?
> 
> ` @Throws(MqttException::class) override fun reconnect() = Unit`

It's simply not implemented. The considerations is the afford. If you have an idea what to do here, then please open a pull request
