### ISSUE TITLE
Version 4.1 fails to build

### ISSUE THREAD

**Issue by OKatrych** [hannesa2/paho.mqtt.android#514]
Version 4.0 works fine, but 4.1 fails to build. The reason is that it's using the 3.0 version of the LogcatCoreLib library, which has "Build failed" [status](https://jitpack.io/com/github/AppDevNext/Logcat/LogcatCoreLib/3.0/LogcatCoreLib-3.0.pom) on Jitpack. 

```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.AppDevNext.Logcat:LogcatCoreLib:3.0.

  - https://dl.google.com/dl/android/maven2/com/github/AppDevNext/Logcat/LogcatCoreLib/3.0/LogcatCoreLib-3.0.pom
  - https://repo.maven.apache.org/maven2/com/github/AppDevNext/Logcat/LogcatCoreLib/3.0/LogcatCoreLib-3.0.pom
  - https://plugins.gradle.org/m2/com/github/AppDevNext/Logcat/LogcatCoreLib/3.0/LogcatCoreLib-3.0.pom
  - https://jitpack.io/com/github/AppDevNext/Logcat/LogcatCoreLib/3.0/LogcatCoreLib-3.0.pom
  - https://maven.mountaininfra.net/artifactory/libs-release-local/com/github/AppDevNext/Logcat/LogcatCoreLib/3.0/LogcatCoreLib-3.0.pom
```

**Comment by hannesa2** [comment]
I've no clue what jitpack.io did. I only merge on successful build https://github.com/hannesa2/paho.mqtt.android/pull/491. And now 3.0 is gone 👎

I re-triggered build, and now logcat 3.0 is back and paho.mqtt.android 4.0 should work again 
<img width="667" alt="image" src="https://github.com/hannesa2/paho.mqtt.android/assets/3314607/e48241a4-bfdf-4dc5-93be-0a07d86a4a29">

**Comment by hannesa2** [comment]
Btw, I built a new version too https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.2
