### ISSUE TITLE
Cannot automatically reconnect when cleanSession = true

### ISSUE THREAD

**Issue by hoangchungk53qx1** [hannesa2/paho.mqtt.android#519]
When I set options with parameters like this, I cannot automatically reconnect when the network is lost    
```
val options = MqttConnectOptions()
  options.isAutomaticReconnect = true
  options.isCleanSession = true
```
If I install with these parameters, mqtt can automatically reconnect when losing network and regaining network.

```
val options = MqttConnectOptions()
  options.isAutomaticReconnect = true
  options.isCleanSession = false
```
Is there any way I can still cleanSession = true and isAutoReconnect = true and automatically reconnect ?

**Comment by hoc081098** [comment]
🙏

**Comment by hannesa2** [comment]
Hi @hoangchungk53qx1 please can you share, why you closed it ?
Do you extend your knowledge, or simply frustrated accept the current situation ?

**Comment by hoangchungk53qx1** [comment]
Hi @hannesa2. I realized that when cleaningSession = true. it is impossible to reconnect, this is correct because the client is no longer there, in accordance with MQTT principles.
