### ISSUE TITLE
Gradle Error in version 4.2

### ISSUE THREAD

**Issue by mintheinwin** [hannesa2/paho.mqtt.android#523]
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
 implementation 'com.github.hannesa2:paho.mqtt.android:4.2'

Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugCompileClasspath'.

**Comment by hannesa2** [comment]
https://github.com/hannesa2/paho.mqtt.android#using-this-mqtt-android-client

**Comment by mintheinwin** [comment]
Hi Hannesa2,
The lasted version is 4.2 right?
So I add in the gradle 
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'com.github.hannesa2:paho.mqtt.android:4.2'

After then I'm can't call this method MqttAndroidClient
When I run app to device I got this error with this libraries dependencies

**Comment by hannesa2** [comment]
On my side it works, Please read the link I sent you. -really !-
Then  search for the string `allprojects` and you will be find nothing ... that's the reason

**Comment by mintheinwin** [comment]
Could you send me sample app? I just create new project with java language and then add your library. And then I got this error. Now I was spend time 8 hours.

**Comment by hannesa2** [comment]
> Could you send me sample app?

Do you think I prepare a sample app for you, when you neither read the README nor my answer ?
Some need an extra invitation: I wrote YOU should prepare a failing sample

**Comment by mintheinwin** [comment]
Hi Hannesa2,
I got the solutions , Thanks.

**Comment by AkshayLtts1** [comment]
give me the solution of this.

**Comment by prpatil4** [comment]
Facing the same problem. Gradle is failing  to locate the paho library [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not find com.github.hannesa2:paho.mqtt.android:Tag.

**Comment by prpatil4** [comment]
Can some one help here?

**Comment by prpatil4** [comment]
Additional details:

In top level gradle file
repositories {

        google()

        gradlePluginPortal()
        maven { url "https://jitpack.io" }
        flatDir { dirs 'lib' }


        maven {
            url "https://repo.eclipse.org/content/repositories/paho-snapshots/"

            //url "https://repo.eclipse.org/content/repositories/paho-releases/"
        }


In app gradle file:

//31st Dec 24
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'  //1.2.4
  //  implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
   //Newly added

    implementation fileTree(dir: "lib", include: ["*.aar"])
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.github.hannesa2:paho.mqtt.android:4.2' // 3.3.5

**Comment by hannesa2** [comment]
> url "https://repo.eclipse.org/content/repositories/paho-snapshots/"

pointless

> implementation 'androidx.legacy:legacy-support-v4:1.0.0'

pointless

### Required

`implementation "com.github.hannesa2:paho.mqtt.android:4.3"`

Btw, I should switch to this **maintenance mode** https://github.com/Triple-T/gradle-play-publisher?tab=readme-ov-file#project-status-maintenance-mode as least when it comes with this label 
<img width="149" alt="image" src="https://github.com/user-attachments/assets/f0923683-f9b1-4f89-8d85-4fefee764c6a" />

**Comment by prpatil4** [comment]
Thanks for the quick revert but not able to make out where is the problem.
Here is the gradle output comment::
Failed to resolve: com.github.hannesa2:paho.mqtt.android:4.3
<a href="open.dependency.in.project.structure">[Show in Project Structure dialog](https://github.com/hannesa2/paho.mqtt.android/issues/open.dependency.in.project.structure)</a>
Affected Modules: <a href="openFile:D:/Projects/AndroidProjects/RemoteMonitoringAndControl/[app](openfile:D:/Projects/AndroidProjects/RemoteMonitoringAndControl/app/build.gradle)/build.gradle">app</a>

**Comment by prpatil4** [comment]
Here is the search url which failed :
Failed | https://dl.google.com/dl/android/maven2/com/github/hannesa2/paho.mqtt.android/4.3/paho.mqtt.android-4.3.pom

Is this path correct ?

**Comment by prpatil4** [comment]
Here is the path that it looks for. Is it correct?

Failed | https://dl.google.com/dl/android/maven2/com/github/hannesa2/paho.mqtt.android/4.3/paho.mqtt.android-4.3.pom

**Comment by hannesa2** [comment]
your jitpack maven is wrong

**Comment by prpatil4** [comment]
Hi hannesa2,

Request lease let me know what is wrong in the below. No able to make out. 

repositories {

        google()
        maven { url 'https://jitpack.io' }
        mavenCentral()
        gradlePluginPortal()

        flatDir { dirs 'lib' }


        maven {
          //  url "https://repo.eclipse.org/content/repositories/paho-snapshots/"

            url "https://repo.eclipse.org/content/repositories/paho-releases/"
        }

**Comment by prpatil4** [comment]
Problem is solved!! Thanks
