### ISSUE TITLE
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

### ISSUE THREAD

**Issue by mintheinwin** [hannesa2/paho.mqtt.android#524]
Please don't close my question. I'm so seriously want to solve this issue. 

implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'com.github.hannesa2:paho.mqtt.android:4.2'

Library not working to call some method from library.
When run project app. 
I got this error
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

**Comment by hannesa2** [comment]
Opening 2 issues makes it not better.
See https://github.com/hannesa2/paho.mqtt.android/issues/523#issuecomment-1786715254
Send me a link from not-working-repo or a pull request, this is the only way to investigate the stuff from **your** side
