### ISSUE TITLE
Why foregroundServiceType is added on the last commit?

### ISSUE THREAD

**Issue by SodaSurfer** [hannesa2/paho.mqtt.android#528]
Hi, what is the use of foregroundServiceType and why do we need it and the FOREGROUND_SERVICE_DATA_SYNC permission in this commit?
https://github.com/hannesa2/paho.mqtt.android/commit/8266d647b7fe650ca8d7fd62583efcb2f17df25b

is it possible to use the library without this permission?

thanks

**Comment by hannesa2** [comment]
As you can see, it was part of api34 changes
<img width="434" alt="image" src="https://github.com/hannesa2/paho.mqtt.android/assets/3314607/ae1e6550-2c85-4bb2-b61f-955aeb534bcb">


> is it possible to use the library without this permission?

simply use 4.0

**Comment by SodaSurfer** [comment]
if I'll use v4.0, wouldn't it be missing necessary features?

**Comment by hannesa2** [comment]
The main purpose of the change log is to answer this question 
https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.2
https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.1
