### ISSUE TITLE
API Level 34 on Version 3.5.3

### ISSUE THREAD

**Issue by SM2A** [hannesa2/paho.mqtt.android#548]
Hi
I found release 3.5.3 the most reliable version for me but it isn't compatible with android 14 (API 34). I was wondering weather do you accept any patch on this version or not? I would like to try making version 3.5.3 compatible with android 14.

**Comment by hannesa2** [comment]
https://github.com/hannesa2/paho.mqtt.android/pull/549 If it build, then I can make a version too

**Comment by SM2A** [comment]
Wow
Thanks
I can help if it's needed

**Comment by hannesa2** [comment]
Now I'm busy with other things, please jump into it.
The last issue is 
<img width="1089" alt="image" src="https://github.com/hannesa2/paho.mqtt.android/assets/3314607/98d55df9-c299-49db-af63-a48187e7bf9f">
on master it is fixed, but I forgot how ....

**Comment by SM2A** [comment]
I'm on it

**Comment by SM2A** [comment]
I'm on it

**Comment by SM2A** [comment]
I'm on it

**Comment by hannesa2** [comment]
> I found release 3.5.3 the most reliable version

Please enlighten me, why is 3.5.3 better ?

**Comment by SM2A** [comment]
> > I found release 3.5.3 the most reliable version
> 
> Please enlighten me, why is 3.5.3 better ?

Since version 4.x I also see [PingWorker not work](https://github.com/hannesa2/paho.mqtt.android/issues/502) witch causes me so many connection losses. In some cases that I leave device idle for a while, device is totally disconnected. So in my testings version 3.x is more suitable for me.

**Comment by hannesa2** [comment]
Interesting that's an issue for you.
It's normal, that with Pingworker it loose connection, so it needs a reconnect. If it don't reconnect, then it's an issue ...

**Comment by hannesa2** [comment]
In my point of view it's better to use 4.x instead of using battery draining 3.x.
Maybe it's just too much logging in 4.x. Only important is a well message receiving library

**Comment by hannesa2** [comment]
Here you go https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6

**Comment by sagarsmartsense** [comment]
After updating to 3.6, I am getting an error:

error: cannot access MqttAndroidClient
    public info.mqtt.android.service.MqttAndroidClient mqttAndroidClient;

**Comment by hannesa2** [comment]
> @hannesa2 After updating to 3.6, I am getting an error:
> 
> error: cannot access MqttAndroidClient public info.mqtt.android.service.MqttAndroidClient mqttAndroidClient;

@sagarsmartsense A sample is required

**Comment by sagarsmartsense** [comment]
@hannesa2 Hey, It's working fine now. After updating the Gradle plugin and giving support to Android 14, everything working fine.

Thanks for the help.

**Comment by sagarsmartsense** [comment]
@mayurappscripde Gradle 8.4
