### ISSUE TITLE
PROBLEM TO POPULATE  TEXTVIEW WITH MESSAGE_ARRIVED

### ISSUE THREAD

**Issue by EltecDev** [hannesa2/paho.mqtt.android#587]
Hi, I´m having problems in the section message_arrived, when i receive an answer i want to show it in a textview with:  binding.textViewPacks.text=String(mqttMessage.payload), but textview is not changed but the message is received because a can watch it in a logd()
I've used 
mHandler = new Handler(Looper.getMainLooper())
runOnUiThread{}
Courutiones
Nothing works
I'm using the versión 4.2.3

**Comment by hannesa2** [comment]
When you can see it in log, the library is working.
It looks like a local problem, and without a running sample I can do nothing
