### ISSUE TITLE
Need Android 14 support - App Crashes

### ISSUE THREAD

**Issue by RaghulThavamani** [hannesa2/paho.mqtt.android#625]
MqttService.kt file contains broadcast receiver implementation,

private fun registerBroadcastReceivers() {
        if (networkConnectionMonitor == null) {
            networkConnectionMonitor = NetworkConnectionIntentReceiver()
            **registerReceiver(networkConnectionMonitor, IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION))**
        }
    }
    
as per android document, for android 14, need to pass as third parameter, 
Ex. **registerReceiver(DataReceiver(), intentFilter, Context.RECEIVER_NOT_EXPORTED)**

[ref.](https://developer.android.com/develop/background-work/background-tasks/broadcasts#manifest-declared-receivers)

Kindly update this issue.

**Comment by nur-shuvo** [comment]
Hello.
It is fixed https://github.com/hannesa2/paho.mqtt.android/pull/549/commits/b4c8914d96e7e4701b437457666823ea2329445d
Please try latest version.

**Comment by hannesa2** [comment]
Please reopen, if current version doesn't fix it
