### ISSUE TITLE
is the tokenmap can not release

### ISSUE THREAD

**Issue by baneyue** [hannesa2/paho.mqtt.android#679]
What is the reason for the continuous increase in objects in the tokenMap during long-term application operation. Running 12 will take up a lot of memory

![企业微信截图_1724720541784](https://github.com/user-attachments/assets/ce7f7694-a8b3-4c5b-b024-30032adf2052)

**Comment by hannesa2** [comment]
It's a left over from Eclipse project https://github.com/eclipse/paho.mqtt.android/blob/a6496553bd07886bb1608e6e3aa739c38f26700a/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttAndroidClient.java#L136-L138

If you have a better idea, please make a pull request

**Comment by hannesa2** [comment]
This is a minor improvement https://github.com/hannesa2/paho.mqtt.android/pull/680

**Comment by hannesa2** [comment]
But the main question is still there: Why they handle token by tokenNumber and access it by tokenNumber instead of using token instead and use a mutableList ?

**Comment by baneyue** [comment]
https://github.com/eclipse/paho.mqtt.android/issues/455

i was use qos 0

**Comment by baneyue** [comment]
https://github.com/eclipse/paho.mqtt.android/issues/455

i was use qos 0

**Comment by hannesa2** [comment]
> What is the reason for the continuous increase in objects in the tokenMap during long-term application operation. Running 12 will take up a lot of memory
> 
> ![企业微信截图_1724720541784](https://private-user-images.githubusercontent.com/1902581/361620140-ce7f7694-a8b3-4c5b-b024-30032adf2052.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzExNTIsIm5iZiI6MTcyNDgzMDg1MiwicGF0aCI6Ii8xOTAyNTgxLzM2MTYyMDE0MC1jZTdmNzY5NC1hOGIzLTRjNWItYjAyNC0zMDAzMmFkZjIwNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDc0MDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmExNzJkZTZhNjdiOGIzNTA5NDc0YWY5NDJiY2NjOTY3MmRjMDY0MzE4ZGMwMmUxYzg1NWQ4NzM4MDg4YTYwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-0m8RMuzrHn-_vYtx8aw3wO3wIZSad8OV8LjkSB6ZyI)

Btw, how to see the content of this table on my local running instance ?

**Comment by baneyue** [comment]
I found this problem. When I use the master branch, I won't have this issue, but when I use 3. x, I have this problem. 

This should be caused by broadcastReceiver, because my usage scenario is sending a string of data in 1 second. 
It is estimated that when the performance is tight on Android 6, 
broadcastReceiver is easily lost, resulting in tokenMap not receiving callbacks

so i think need not to replace SparseArray to List。

you can merge the flow to 3.x branch to replace the BroadcastReceiver

**Comment by hannesa2** [comment]
I'm somehow lost here 

The pull request solves nothing, but I should merge it? -no-

Master comes with another issue, means a lost receiver? But 3.x us fine?

It's another blueprint that I only should merge existing pull requests and anything else is a waste of time. Right?

**Comment by baneyue** [comment]
Wait, I'm still testing

**Comment by baneyue** [comment]
@hannesa2 this problem may be the qos =0 and when send failure，it will not callback deliveryComplete

**Comment by hannesa2** [comment]
Nice.
To have a clear understanding:

The causing issue is a resulting non-remove of these in _popSendDetails_ ? Am I right ?

            val topic = mapTopics.remove(messageToken)
            val activityToken = mapActivityTokens.remove(messageToken)
            val invocationContext = mapInvocationContexts.remove(messageToken)

**Comment by baneyue** [comment]
otherwise

1.  I think it's better to use HashMap or SparseArray instead of MutableList
2.  also, I suggest that all of project use Dispatchers IO replaces Dispatchers Main

**Comment by baneyue** [comment]
My current plan is to set qos=0 without caching, so there will be no callbacks; A better approach would be to specify a timeout period, after which the token will be removed if there is no callback.

**Comment by hannesa2** [comment]
As far as I understand, you run into this with a lot of publishes, which all run into (network?) errors. Am I right ? 
The next thing is, how do you measure the memory usage. https://github.com/hannesa2/paho.mqtt.android/issues/679#issuecomment-2314575452

**Comment by baneyue** [comment]
The network is weak or congested, and there has been no disconnection

Actually, I'm not sure what the root cause is, but after running for a long time, some callbacks cannot be received, causing those caches to be unable to be released, and the memory growth is not fast. Through profile analysis, the object continues to grow, which is quite observable for our low-end devices, causing the application to slow down

**Comment by hannesa2** [comment]
It's not a miracle, when you do a lot on low end device, that it will become slow.
Solutions have different faces, but to know, if a solution is useful, you need an evidence.
I still wait for https://github.com/hannesa2/paho.mqtt.android/issues/679#issuecomment-2314575452
