### ISSUE TITLE
dependencyResolutionManagement should be put in settings.gradle

### ISSUE THREAD

**Issue by adazem009** [hannesa2/paho.mqtt.android#713]
The documentation (https://jitpack.io/#hannesa2/paho.mqtt.android) states that this block:
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
```
should be added to the root `build.gradle`. Shouldn't it be put in `settings.gradle` instead? At least that's what's working for me.

**Comment by hannesa2** [comment]
When it works for you, then all is fine.
I at least never use settings.gradle for this, but I'm happy when I could see a running sample from you

**Comment by adazem009** [comment]
> When it works for you, then all is fine.
> I at least never use `settings.gradle` for this, but I'm happy when I could see a running sample from you

I was getting errors when I used `build.gradle`, so that's why I tried `settings.gradle`. I'll try it again and will send it here today...

**Comment by adazem009** [comment]
@hannesa2 This is the error I'm getting with `build.gradle`:
`ould not find method dependencyResolutionManagement() for arguments [build_eu6vx9yp55mrryw3x5fjgl63q$_run_closure1@7d1cbb08] on root project 'Test' of type org.gradle.api.Project.`
It works without any issues when I use `settings.gradle`, I'm not sure why.

**Comment by hannesa2** [comment]
A *running* sample is always welcome. This makes it easy to investigate and is mostly the only way to figure out what's wrong

**Comment by adazem009** [comment]
> A **_running_** sample is always welcome. This makes it easy to investigate and is mostly the only way to figure out what's wrong

Here it is: [dependencyResolutionManagement_error.zip](https://github.com/user-attachments/files/17908853/dependencyResolutionManagement_error.zip)
(I'm using Gradle 8.7)

**Comment by hannesa2** [comment]
I see, you use the new project structure ! (I've no clue how to name it) 
There the dependencies are in `settings.gradle` and I was able to build by 
### `build.gradle` (app)
<img width="747" alt="image" src="https://github.com/user-attachments/assets/696bfd27-b95a-48c3-9c60-f48cd3d225fd">

### `build.gradle`
<img width="775" alt="image" src="https://github.com/user-attachments/assets/b10dda50-05ac-4bfd-9364-6bd6227be539">

### `settings.gradle`
<img width="776" alt="image" src="https://github.com/user-attachments/assets/07782cad-d4af-4f73-b2a0-54695021b2fc">
